import { checkContent } from './contentModerationService';

// This is a list of words/names/phrases/organizations that are considered offensive and should not be used in this application.
const OFFENSIVE_WORDS = [
  'ejaculate',
  'ejaculation',
  'arsehead',
  'arse',
  'arsehole',
  'asshat',
  'assfart',
  'shite',
  'dumbass',
  'dumb fuck',
  'dyke',
  'load of shit',
  'full of shit',
  'horseshit',
  'dogshit',
  'son of a bitch',
  'son of a whore',
  'prick',
  'shit',
  'shithead',
  'fuck face',
  'finger yourself',
  'milf',
  'dilf',
  'Stalin',
  'Satan',
  'Nazi',
  'Vladimir Putin',
  'Kremlin',
  'Putin',
  'Pro-Putin',
  'Pro-Russia',
  'Pro-Hitler',
  'Benjamin Netanyahu',
  'Viktor Orbán',
  'Xi Jinping',
  'Ayatollah Ali Khamenei',
  'Ahmed al‑Sharaa',
  'Adolf Hitler',
  'Hitler',
  'Augusto Pinochet',
  'Alberto Fujimori',
  'Lee Kuan Yew',
  'Recep Tayyip Erdoğan',
  'Boris Yeltsin',
  'unified reich',
  'Javier Milei',
  'Donald Trump',
  'Trump',
  'Trumpism',
  'Trump2028',
  'Make America Great Again',
  'Maga',
  'Mein Kampf',
  'fascist',
  'faggot',
  'fuck',
  'fuck you',
  'fuckbag',
  'fuck off',
  'fuck me',
  'fucking',
  'bastard',
  'spastic',
  'retard',
  'retarded',
  'bitch',
  'pussy',
  'asshole',
  'ass',
  'anal',
  'anus',
  'dick',
  'dickhead',
  'cunt',
  'penis',
  'penal',
  'scrotum',
  'vagina',
  'dildo',
  'neo-nazi',
  'proud boys',
  'oathkeepers',
  'Al Qaeda',
  'Taliban',
  'ISIS',
  'Qatar',
  'Osama Bin Laden',
  'qanon',
  'cum',
  'cumming',
  'Kim Jong Un',
  'Hamas',
  'Bashar al-Assad',
  'Hayʼat Tahrir al-Sham',
  'Hezbollah',
  'Houthi',
  'wanker',
  'whore',
  'white power',
  'white supremacy',
  'white supremacist',
  'coon',
  'cocksucker',
  'nigga',
  'nigger',
  'Stalin',
  'Hentai',
  'porn',
  'pornhub',
  'pornography',
  'pornographic',
  'pedo',
  'pedophile',
  'kill yourself',
  'kys',
  'rape',
  'rapist',
  'raped',
  'fucked',
  'fucked up',
  'motherfucker',
  'motherfucking',
  'J.D. Vance',
  'Elon Musk',
  'Tulsi Gabbard',
  'Tucker Carlson',
  'Jesse Watters',
  'Kari Lake',
  'Marco Rubio',
  'Jeffrey Epstein',
  'Ghislaine Maxwell',
  'Rudy Giuliani',
  'Linda McMahon',
  'Chuck Grassley',
  'Steve Bannon',
  'Tim Scott',
  'Niki Haley',
  'Asa Hutchinson',
  'Francis Suarez',
  'Will Hurd',
  'Perry Johnson',
  'Vivek Ramaswamy',
  'Kash Patel',
  'Dan Bongino',
  'Paul Dans',
  'Winsome Earle-Sears',
  'Mike Johnson',
  'Kyle Rittenhouse',
  'Rick Scott',
  'Ron DeSantis',
  'Casey DeSantis',
  'Pam Bondi',
  'Emil Bove',
  'Pete Hegseth',
  'Ted Cruz',
  'Robert F. Kennedy Jr.',
  'Byron Donalds',
  'Russel Vought',
  'Jon Voight',
  'Marjorie Taylor Greene',
  'Joe Wilson',
  'Lauren Boebert',
  'Matt Gaetz',
  'Alice Johnson',
  'Jim Jordan',
  'Melania Trump',
  'Donald Trump Jr.',
  'Laura Trump',
  'Eric Trump',
  'Ivanka Trump',
  'Barron Trump',
  'Mitch McConnell',
  'Doug Burgum',
  'Tom Homan',
  'John Roberts',
  'Amy Coney Barrett',
  'Clarence Thomas',
  'Lindsey Graham',
  'Samuel Alito',
  'Brett Kavanaugh',
  'Neil Gorsuch',
  'Aileen Cannon',
  'Tommy Tuberville',
  'Brandon Carr',
  'Elaine Pelino',
  'Dr. Oz',
  'Mehmet Oz',
  'Julie Fedorchak',
  'Greg Abbott',
  'Enrique Tarrio',
  'Steward Rhodes',
  'Eric Adams',
  'Tammy Bruce',
  'Matt Walsh',
  'Brad Schimel',
  'Katie Britt',
  'Bernie Mareno',
  'Tom Cotton',
  'Gabe Evans',
  'Rand Paul',
  'Bill Cassidy',
  'Markwayne Mullin',
  'John Thune',
  'Michael Todd Chrisley',
  'Julie Chrisley',
  'Dean Cain',
  'Kelly Ayotte',
  'Cory Mills',
  'Larry Kudlow',
  'John Barraso',
  'Sarah Palin',
  'Robert Aderholt',
  'James Lankford',
  'Steve Scalise',
  'Kanye West',
  'Bill Cosby',
  'Ben Shapiro',
  'Derek Chauvin',
  'Karoline Leavitt',
  'Dave McCormick',
  'Chris Rufo',
  'John Eastman',
  'Kenneth Chesebro',
  'Sidney Powell',
  'Mark Meadows',
  'Howard Lutnick',
  'Mike Waltz',
  'Tim Sheehy',
  'John Ratcliffe',
  'Steve Witkoff',
  'Laura Loomer',
  'Rush Limbaugh',
  'Doug Collins',
  'Lee Greenwood',
  'Herschel Walker',
  'Dennis Quaid',
  'Mike Kehoe',
  'Brian Kemp',
  'Alina Habba',
  'Chip Roy',
  'David Richardson',
  'Kristi Noem',
  'Elise Stefanik',
  'Jay Clayton',
  'Boris Epstein',
  'Ed Martin',
  'Sean Duffy',
  'Miley Biggs',
  'Jim Banks',
  'Alex Bruesewitz',
  'Susan Collins',
  'Robert Giuffra',
  'Mike Lindell',
  'Eric Lendrum',
  'Harmeet Dhillon',
  'Ryan Walters',
  'Stephen Miran',
  'Felix Barry Moore',
  'Jeanine Pirro',
  'J. K. Rowling',
  'Nicki Minaj',
  'Kenneth Petty',
  'Mike Haridopolos',
  'Josh Hawley',
  'Derek Schmidt',
  'Jefferson Shreve',
  'Mike Lee',
  'John Kennedy',
  'Andy Biggs',
  'Craig Goldman',
  'Derrick Van Orden',
  'Jeff Bezos',
  'Scott Bessent',
  'John Curtis',
  'Lisa McClain',
  'Monica Crowley',
  'Brooke Rollins',
  'Dabney Friedrich',
  'Jeff Sessions',
  'Richard Hudson Jr.',
  'Andrea Lucas',
  'Mike Flood',
  'Kelly Armstrong',
  'Devin Nunes',
  'Hulk Hogan',
  'Earl LeRoy Carter',
  'Buddy Carter',
  'Kevin Roberts',
  'Mike Braun',
  'Rodney Scott',
  'Steve Moore',
  'Jeffrey Crank',
  'Robert Wolf',
  'Andrew Puzder',
  'Joshua Divine',
  'Ric Grenell',
  'Salvatore Cordileone',
  'Vance Boelter',
  'Charlie Kirk',
  'Kevin Stitt',
  'Paul Szypula',
  'Bill Hagerty',
  'Jeff Landry',
  'Nick Sortor',
  'Haile McAnally',
  'Thom Tillis',
  'Joe Lombardo',
  'David Schweikert',
  'Kevin Kiley',
  'Anna Paulina',
  'Stephen Miller',
  'Jason Smith',
  'Randy Feenstra',
  'John Sauer',
  'Zach Rehl',
  'Jessica Watkins',
  'Kenneth Harrelson',
  'Kyle Young',
  'James Ho',
  'Don Willett',
  'Henry McMaster',
  'Larry Rhoden',
  'Ashley Moody',
  'Mike DeWine',
  'Robert Morss',
  'Kelly Meggs',
  'Greg Gutfeld',
  'Joseph Hackett',
  'Gary Palmer',
  'Dominic Pezzola',
  'Tim Hale',
  'Sean Combs',
  'Dustin Burrows',
  'Bret Baier',
  'Marlin Stutzman',
  'Elliot Gaiser',
  'Dale Strong',
  'James Gallagher',
  'Michael Whatley',
  'Joni Ernst',
  'Andy Harris',
  'Nancy Mace',
  'Bruce Westerman',
  'Joe Gruters',
  'Sergio Gor',
  'Ken Paxton',
  'Brendan Carr',
  'John Cornyn',
  'Sarah Huckabee Sanders',
  'Gregory Katsas',
  'Justin Walker',
  'Steve Womack',
  'Kevin Hern',
  'Alex Stein',
  'Tate Reeves',
  'Corey Lewandowski',
  'Greg Gianforte',
  'Jeffrey Wall',
  'Marsha Blackburn',
  'Bill Lee',
  'Michael Bartels',
  'Joe Lewis',
  'Alex Dwyer',
  'Tony Fabrizio',
  'Markwayne Mullin',
  'Kay Ivey',
  'Clayton Fuller',
  'Joe Hathaway',
  'Ralph Norman',
  'Jim Pellin',
  'Debra Fischer',
  'Jon Husted',
  'Sheri Biggs',
  'Ashley Hinson',
  'Chris LaCivita',
  'Jimmy Patronis Jr.',
  'Randy Fine',
  'Shelley Moore Capito',
  'James Comey',
  'Glenn Youngkin',
  'Phil McGraw',
  'Michele Morrow',
  'Tom Tiffany',
  'Bryan Steil',
  'Virginia Foxx',
  'Rick Snyder',
  'Mike Rogers',
  'Stacy Garrity',
  'Todd Hunter',
  'Charlie Geren',
  'Rob Bresnahan Jr.',
  'Addison McDowell',
  'Benny Johnson',
  'John Boozman',
  'Kimberly Guilfoyle',
  'Paul Ingrassia',
  'Kid Rock',
  'Robert James Ritchie',
  'Callista Gingrich',
  'Lindsey Halligan',
  'Nick Begich III',
  'Brad Little',
  'Mark Gordon',
  'Phil Scott',
  'Spencer Cox',
  'Kim Reynolds',
  'Michael Collins Jr.',
  'Ashley Moore',
  'Patrick Harrigan',
  'Jim Justice',
  'Heather Honey',
  'Christopher S. Ripley',
  'Anna Luna',
  'Thomas Barrett',
  'David Valadao',
  'Kandiss Taylor',
  'James Murphy',
  'Scott Mayer',
  'Ryan Mackenzie',
  'Gloria Gaynor',
  'Julia Letlow',
  'Jordan Emery Pratt',
  'Laura Ingraham',
  'Troy Downing',
  'Sean Hannity',
  'Glenn Beck',
  'Charlie Hurt',
  'Mike Dunleavy',
  'Joe Rogan',
  'Jake Lang',
  'Adam Johnson',
  'Alex Jones',
  'Liz Wheeler',
  'Megyn Kelly',
  'Bryan Kohberger',
  'Dylan Roof',
  'Robert Durst',
  'Ted Bundy',
  'herpes',
  'genitalia',
  'genitals',
  'sex trafficking',
  'kiss my ass',
  'suck my dick',
  'eat a dick',
  'blew my load',
  'blewmyload',
  'titty fuck',
  'titty',
  'nipples',
  'paizuri',
  'shotacon',
  'butt plug',
  'buttplug',
  'Ku Klux Klan',
  'KKK',
  'Department of Government Effeciency',
  'Lynching',
  'buttlicker',
  'jizz',
  'cumshot',
  'blowjob',
  'titties',
  'titjob',
  'handjob',
  'thighjob',
  'footjob',
  'cunnilingus',
  'butt fuck',
  'buttfuck',
  'bitch tits',
  'bitch ass',
  'masterbate',
  'masterbating',
  'masterbated',
  'horny',
  'horny bitch',
  'slut',
  'slutty',
  'Bollocks',
  'bollocks',
  'cumdumpster',
  'cum dumpster',
  'testicles',
  'neek',
  'twat',
  'gooning',
  'buttfucker',
  'butt fucker',
  'buttfucked',
  'butt fucked',
  'pussy hole',
  'blow me',
  'blowme',
  'bulge',
  'Under Seige',
  'The Art of the Deal',
  'Aligator Alcatraz',
  'Let\'s Go Brandon',
  'Truth Social',
  'Young Republicans',
  'Immigration Customs Enforcement',
  'Children\'s Health Defense',
  'Medical Ethics Defense Act',
  'The Federalist Society',
  'Heritage Foundation',
  'Fox News',
  'Newsmax',
  'Sinclair Broadcast Group',
  'Nexstar Media Group',
  'Turning Point USA',
  'SAVE America Act',
  'Safeguard American Voter Eligibility Act',
  'One America News Network',
  'Project 2025',
  'National Socialist Movement',
  'Order of the Black Sun',
  'Blood Tribe',
  'Patriot Front',
  'Atomwaffen Division',
  'Phyllis Schlafly Eagles',
  'Religious Liberty Commission'
  // I do not approve any of these words, names, organizations and/or phrases being used in this application.
];

export const containsOffensiveContent = async (content: string, userId: string) => {
  // First do a quick local check using word boundaries to match whole words only
  const lowercaseContent = content.toLowerCase();
  const foundWords = OFFENSIVE_WORDS.filter(word => {
    const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // (?<!\w) and (?!\w) act like \b but also work when the entry starts/ends
    // with a non-word character (e.g. "Jr." ending with a period).
    const wordBoundaryRegex = new RegExp(`(?<!\\w)${escaped}(?!\\w)`, 'i');
    return wordBoundaryRegex.test(content);
  });

  if (foundWords.length === 0) {
    return {
      isOffensive: false,
      offendingWords: []
    };
  }

  // If offensive words were found locally, handle violation directly (server-side)
  // This avoids making unnecessary HTTP calls when already in a server context
  if (typeof window === 'undefined') {
    // Server-side: directly handle violation
    const { handleContentViolation } = await import('./violationHandler');
    const violationResult = await handleContentViolation(userId, foundWords);
    
    return {
      isOffensive: true,
      offendingWords: foundWords,
      violationResult
    };
  }

  // Client-side: verify with the server via HTTP
  const result = await checkContent(content, userId);

  return {
    isOffensive: !result.isValid,
    offendingWords: result.offendingWords || foundWords,
    violationResult: result.violationResult
  };
};